# Site settings
title: "First Casino Gambling"
description: "Your premier online gaming destination"
url: "https://hongduc5729l-max.github.io/"
baseurl: "/First-Casino-Gambling"

# Include XML files
include:
  - sitemap.xml
  - robots.txt

# Exclude .htaccess as it's not supported on GitHub Pages
exclude:
  - .htaccess

# Markdown settings
markdown: kramdown
highlighter: rouge

permalink: pretty
